output_path: output/Identical/
# Dataset Section
eval_datasets:
  - RAGTruth
  - FaithBench

# Eval Pipeline
pipeline:
  - IdenticalCorrectionModel:
      model_name: Identical
  - ClaimExtractor:
      model: meta-llama/llama-3.3-70b-instruct
      output_column: extracted
      RPS: 20
      num_proc: 20
      api_key_env: OPENROUTER_API_KEY   
  - Rouge:
      model_name: Rouge#L
      context_column: claim
  - HHEM:
      model_name: HHEM#Open-claim
      model_path: vectara/hallucination_evaluation_model
      claim_column: extracted
  - Minicheck:
      model_name: Minicheck#7B-claim
      claim_column: extracted
  - FACTSGJudge:
      model_name: FACTSGJudge#Llama-3.3-70b-json
      model: meta-llama/llama-3.3-70b-instruct
      RPS: 20
      num_proc: 20
      api_key_env: OPENROUTER_API_KEY
