output_path: output/Identical/
# Dataset Section
eval_datasets:
  # - RAGTruth
  # - FAVA
  # - FaithBench
  - FACTSGrounding

# Eval Pipeline
pipeline:
  - IdenticalCorrectionModel:
      model_name: Identical
  - ClaimExtractor:
      model_path: meta-llama/llama-3.3-70b-instruct
      output_column: extracted
      RPS: 20
      num_proc: 20
  - Rouge:
      model_name: Rouge#L
      context_column: claim
  - HHEM:
      model_name: HHEM#2.1-claim
      model_path: vectara/HHEM-2.1
      claim_column: extracted
  - Minicheck:
      model_name: Minicheck#7B-claim
      claim_column: extracted
  - FACTSGJudge:
      model_name: FACTSGJudge#Llama-3.3-70b-json
      RPS: 20
      num_proc: 20
