output_path: output/Identity/
# Dataset Section
eval_datasets:
  - RAGTruth
  - FaithBench
  # - FAVA
  # - FACTSGrounding

# Eval Pipeline
pipeline:
  - IdenticalCorrectionModel:
      model_name: Identity
  - ClaimExtractor:
      model: meta-llama/Llama-3.3-70B-Instruct-Turbo
      base_url: https://api.together.xyz/v1/
      output_column: extracted
      RPS: 20
      num_proc: 20
      api_key_env: TOGETHER_API_KEY   
  - Rouge:
      model_name: Rouge#L
      context_column: claim
  - HHEM:
      model_name: HHEM#Open-claim
      model_path: vectara/hallucination_evaluation_model
      claim_column: extracted
  - Minicheck:
      model_name: Minicheck#7B-claim
      claim_column: extracted
  - FACTSGJudge:
      model_name: FACTSGJudge#Llama-3.3-70b-json
      model: meta-llama/Llama-3.3-70B-Instruct-Turbo
      base_url: https://api.together.xyz/v1/
      RPS: 20
      num_proc: 20
      api_key_env: TOGETHER_API_KEY
